### ISSUE TITLE
error in local shiny server

### ISSUE THREAD

**Issue by ignacio82** [hrbrmstr/taucharts#14]
I'm not sure if this is an error with taucharts or my shiny server.

When I use Rstudio on my local computer to my taucharts example works well. But, when I try to load it on my local shiny server i get this error:

```
Error: do not know how to convert 'x' to class “POSIXct”
```

Thanks for the help!

**Comment by hrbrmstr** [comment]
Re-install from github. We've been in furious active development on the main branch (which is my fault)

**Comment by ignacio82** [comment]
just did, the error did not go away :(
I'm using docker to run shiny server https://registry.hub.docker.com/u/rocker/shiny/

**Comment by timelyportfolio** [comment]
working on this now @ignacio82 ; @hrbrmstr guess we should move to `devel` branch since our "continuous integration" isn't working so well with no tests :)

**Comment by timelyportfolio** [comment]
@ignacio82 let me know if #17 did not fix it

**Comment by ignacio82** [comment]
@timelyportfolio it works! :+1:
