### ISSUE TITLE
add tasks (maybe undocumented)

### ISSUE THREAD

**Issue by timelyportfolio** [hrbrmstr/taucharts#20]
I have found it very useful for things like #19 to add the ability for power users to customize htmlwidgets after render.  Without this little hook, `htmlwidgets` make it very difficult to perform this behavior.  Here is the standard bit of code I have been including.

```
    // set up a container for tasks to perform after completion
    //  one example would be add callbacks for event handling
    //  styling
    if (!(typeof x.tasks === "undefined") ){
      if ( (typeof x.tasks.length === "undefined") ||
       (typeof x.tasks === "function" ) ) {
         // handle a function not enclosed in array
         // should be able to remove once using jsonlite
         x.tasks = [x.tasks];
      }
      x.tasks.map(function(t){
        // for each tasks call the task with el supplied as `this`
        t.call(el);
      })
    }
```

In the example from #19, a user could then do.

``` r
tc %>%
  tau_tasks( htmlwidgets::JS("function(){ d3.select(this).selectAll().style('fill','black') }")
```

@hrbrmstr, would this be ok to add?  So far I have been adding it undocumented, but I could add a `tau_tasks` function or something similar.

**Comment by hrbrmstr** [comment]
Oh yeah. That's super-handy. I was thinking of also adding a function to add arbitrary CSS rules, too

**Comment by timelyportfolio** [comment]
working on it now
