### ISSUE TITLE
Custom color palettes not working with legend

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/taucharts#24]
```
tauchart(mtcars) %>%
  tau_point("wt", "mpg", color="cyl") %>%
  tau_color_tableau() %>% 
  tau_legend()
```

![image](https://cloud.githubusercontent.com/assets/509878/9095574/fd812680-3b85-11e5-83c6-a8de2072dcff.png)

When I use Developer Tools to inspect it, it _looks_ like the color should be being applied, but it's not showing up.

**Comment by timelyportfolio** [comment]
Looks like just needs some extra `CSS` to color the `div` used in the legend.  `div` does not use `fill` like `SVG` elements.  I'll submit pull in just a bit after a little more testing.

**Comment by hrbrmstr** [comment]
thx. I thought it might be something like that. I also need to file an
issue regarding widget size since I cld not really duplicate the example on
the taucharts home page at all sizing-wise.

**Comment by timelyportfolio** [comment]
Ok, want me to pull `master`?

**Comment by hrbrmstr** [comment]
actually, i _just_ sync'd dev with master (including your cleanup PR) so we can work off of that for a while

**Comment by timelyportfolio** [comment]
Dang, this is going to be trickier than I thought, and might be best handled in the legend plugin.  Can get color, but then behavior is different.

**Comment by hrbrmstr** [comment]
it did look like they did some "creative" stuff there. i'm not sure they
really thought through custom colors, but then again it's only at 0.5.0 so
they def get some slack :-)

**Comment by timelyportfolio** [comment]
Think I'm just tired.  I think it is complete.

**Comment by timelyportfolio** [comment]
One thing is the legend does not match the `opacity` of the `svg`.  Even though the legend plugin does not do this, I guess we could since we are overriding `CSS` anyways.  Is it worth it?

**Comment by hrbrmstr** [comment]
mebbe post as a feature req in the taucharts lib?
