### ISSUE TITLE
custom color palette?

### ISSUE THREAD

**Issue by ignacio82** [hrbrmstr/taucharts#29]
Is there a way to use a custom palette? The help file only mentions "tableau10medium", "gray5", "colorblind10", "purplegray12", "bluered12", "greenorange12", "cyclic".

```
library(taucharts)
tauchart(mtcars) %>%
  tau_point("wt", "mpg", color="cyl") %>%
  tau_color_tableau(palette = "bluered12") %>% 
  tau_legend()
```

Can I use, for example, [this one](http://colorbrewer2.org/?type=diverging&scheme=Spectral&n=3)?

Thanks!

**Comment by hrbrmstr** [comment]
Please take a look at the whole package help. It covers tau_color_brewer
(which that is) as well as a host of others. The `tau_color_manual`
function really lets you use any palette you can generate (which is really
any palette).

**Comment by ignacio82** [comment]
Thanks!

```
library(taucharts)
tauchart(mtcars) %>%
  tau_point("wt", "mpg", color="cyl") %>%
  tau_color_manual(c("#fc8d59", "#ffffbf", "#99d594")) %>% 
  tau_legend()
```
