### ISSUE TITLE
Control graphic width / height?

### ISSUE THREAD

**Issue by jeremiahpslewis** [hrbrmstr/taucharts#37]
Perhaps this is not the place for a how-to question, but is there a method in the package for changing the width of a graphic? I've been looking at tauchartsOutput, but am not sure whether/how this applies in a non-shiny, static doc context.

**Comment by jeremiahpslewis** [comment]
This seems to work: `tau_add_css_rule(".taucharts.html-widget-static-bound {width: 100% !important;}")`

**Comment by hrbrmstr** [comment]
Oh nice! Thx for that. Debugging the sizing was on the TODO. I'll add that
in.

**Comment by timelyportfolio** [comment]
While this works, I'm not sure this is the best approach. Ok if we test a little more?

**Comment by hrbrmstr** [comment]
definitely. height is still an issue. prbly all due to TauCharts being full
of `div`s & not just an SVG
