### ISSUE TITLE
CSS Rules not local to a single graphic

### ISSUE THREAD

**Issue by jeremiahpslewis** [hrbrmstr/taucharts#39]
When a css rule is added to a single graphic, e.g. `tau_add_css_rule(".axis_rooty:not(.facet-axis) .tick:nth-child(2n+2) text {opacity: 0;}")`, the rule takes effect for all graphics on the .Rmd HTML page. It's probably a good idea to nest all rules within a chart id, so that different themes can be applied to different graphics.

**Comment by hrbrmstr** [comment]
the `{{ID}}` helper (check the function help) doesn't target each
specifically?

**Comment by jeremiahpslewis** [comment]
Thanks. Sorry, missed that in the documentation. What do you think about throwing a message when {{ID}} is not part of a css rule? It doesn't seem like a great idea to use a html widget to inject page-wide css.

**Comment by jeremiahpslewis** [comment]
`if(!grepl(css_grep, css)) {message("CSS Rules without {{ID}} are applied to entire document.")}`

**Comment by hrbrmstr** [comment]
I think that could be arranged :-)

**Comment by jeremiahpslewis** [comment]
Thanks! Looks great.
