### ISSUE TITLE
error in as_tauchart roxygen example

### ISSUE THREAD

**Issue by timelyportfolio** [hrbrmstr/taucharts#40]
error in these [lines](https://github.com/hrbrmstr/taucharts/blob/master/R/as_tauchart.r#L16-L17).  I would fix but I'm not sure what the values should be.

**Comment by hrbrmstr** [comment]
fixed! thx

**Comment by timelyportfolio** [comment]
one more little one https://github.com/hrbrmstr/taucharts/blob/master/R/as_tauchart.r#L34-L35

`gg` should be `gg_m2`

**Comment by hrbrmstr** [comment]
man, i shld rly know better than to try to `s/oldthing/newthing` without testing :-(

**Comment by timelyportfolio** [comment]
sorry, but spelling.  would fix but don't want to create gh conflicts.

`taucahrt`
https://github.com/hrbrmstr/taucharts/blob/3f49147771b86e52cc7f84f618a0de5ffb30bb82/R/as_tauchart.r#L4

**Comment by hrbrmstr** [comment]
thx
