### ISSUE TITLE
Ordered factors do not work.

### ISSUE THREAD

**Issue by jeremiahpslewis** [hrbrmstr/taucharts#45]

**Comment by jeremiahpslewis** [comment]
mtcars$gear <- factor(mtcars$gear, levels = c(3,4,5), ordered = TRUE)
tauchart(mtcars) %>% tau_point("mpg", "wt", color = "gear") %>% tau_legend()

**Comment by timelyportfolio** [comment]
Well, they work except on the legend, which I'm tracking in https://github.com/TargetProcess/tauCharts/issues/57.  By coincidence, the reworked legend just got pushed to `master` this morning, so I'm testing it now.  I'll wait for an official release before a pull.

**Comment by timelyportfolio** [comment]
@jlewis91 would love for you to test if possible https://github.com/timelyportfolio/taucharts/tree/devel/tau_legend_update.  It seems to work.   I have not had a chance to run all the examples to make sure there are no regressions.

### 3,4,5

```
devtools::install_github("timelyportfolio/taucharts@devel/tau_legend_update"
library(taucharts)

mtcars$gear <- factor(mtcars$gear, levels = c(3,4,5), ordered = TRUE)
tauchart(mtcars) %>% tau_point("mpg", "wt", color = "gear") %>% tau_legend()
```

![image](https://cloud.githubusercontent.com/assets/837910/9316685/24d756bc-44fc-11e5-9f7d-907851f94a9b.png)

### 4,3,5

```
# change the order
mtcars$gear <- factor(mtcars$gear, levels = c(4,3,5), ordered = TRUE)
tauchart(mtcars) %>% tau_point("mpg", "wt", color = "gear") %>% tau_legend()
```

![image](https://cloud.githubusercontent.com/assets/837910/9316677/198f58e0-44fc-11e5-85fd-866dc65d47d9.png)

**Comment by jeremiahpslewis** [comment]
devtools::install_github("timelyportfolio/taucharts@devel/tau_legend_update")

**Comment by jeremiahpslewis** [comment]
Works wonderfully. Thanks!

**Comment by timelyportfolio** [comment]
I just ran through all the examples from the Readme and what I have local.   Everything seems to work fine.

@hrbrmstr, you good with waiting for an official tag bump on `taucharts` master before I submit a pull request, or do you want me to go ahead and submit?

**Comment by jeremiahpslewis** [comment]
How do you guys go about testing before a release? Is there a way of standardizing the process? Might be able to pitch in there. Earlier today there was a non-functional version in the master branch...

**Comment by timelyportfolio** [comment]
I plan to add a bunch of official tests using `testthat`.  Unfortunately on the output side, I think it will be all visual and manual.  I know @hrbrmstr also had a task or comment out there to also add tests.

**Comment by jeremiahpslewis** [comment]
Cool. There is probably a place for some validity tests of the R object that gets passed off to the htmlWidget...those tests could be automatic & would catch the most basic of errors.

**Comment by timelyportfolio** [comment]
Here is on incomplete example from `parcoords` https://github.com/timelyportfolio/parcoords/blob/master/tests/testthat/test_options.R and a fairly complete set from `leaflet` https://github.com/rstudio/leaflet/tree/master/tests/testit.

**Comment by jeremiahpslewis** [comment]
Cool. I'll see if I can grab a bit of time for that.

**Comment by hrbrmstr** [comment]
I'm actually hoping to use phantomjs for static &  dynamic testing

**Comment by hrbrmstr** [comment]
I shld have added that I'm good with waiting for an official release on the JS lib before we incorporate.
