### ISSUE TITLE
When min / max are specified, change autoScale to FALSE

### ISSUE THREAD

**Issue by jeremiahpslewis** [hrbrmstr/taucharts#65]
https://github.com/TargetProcess/tauCharts/issues/146#issuecomment-191148357

**Comment by AdeelK93** [comment]
I know this is a year late, but I've been trying to close some of the issues and update the R taucharts library because it's such a great charting library. Anyways, how does [this](https://github.com/AdeelK93/taucharts) look for fixing your min/max issue?
