### ISSUE TITLE
Can't Install Update

### ISSUE THREAD

**Issue by abresler** [hrbrmstr/taucharts#7]
I think there is some bad code here:

```
/private/var/folders/0n/qhktf1j96b112pf4d6hm2qch0000gn/T/RtmpjA40rj/devtools64aa1b2dfd2/hrbrmstr-taucharts-ad3e17b/R/plugins.:4:1: unexpected input
3: #' @param tau taucharts object
4: <<
```

**Comment by timelyportfolio** [comment]
You're right, the pull came in with conflicts.  I'll clean it up real quickly assuming @hrbrmstr will be ok with the little changes.

**Comment by hrbrmstr** [comment]
argh. pls. yeah. stupid git (both me and the program).

**Comment by hrbrmstr** [comment]
ARGH! I knew I fixed the git weirdness last night but forgot to push it.

it should be ok now.

**Comment by timelyportfolio** [comment]
thanks @hrbrmstr; beat me to it

**Comment by hrbrmstr** [comment]
I promise to never do funky git stuff on 2 hrs of sleep again. and will start the `testthat` scaffolding.
